In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from collections import Counter

In [47]:
data = pd.read_json("News_Category_Dataset_v3.json", lines = True)
data

link  \
0       https://www.huffpost.com/entry/covid-boosters-...   
1       https://www.huffpost.com/entry/american-airlin...   
2       https://www.huffpost.com/entry/funniest-tweets...   
3       https://www.huffpost.com/entry/funniest-parent...   
4       https://www.huffpost.com/entry/amy-cooper-lose...   
...                                                   ...   
209522  https://www.huffingtonpost.com/entry/rim-ceo-t...   
209523  https://www.huffingtonpost.com/entry/maria-sha...   
209524  https://www.huffingtonpost.com/entry/super-bow...   
209525  https://www.huffingtonpost.com/entry/aldon-smi...   
209526  https://www.huffingtonpost.com/entry/dwight-ho...   

                                                 headline   category  \
0       Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1       American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2       23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3       The Funniest Tweets From Parents This Week (Se...  PARENTING   
4       Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   
...                                                   ...        ...   
209522  RIM CEO Thorsten Heins' 'Significant' Plans Fo...       TECH   
209523  Maria Sharapova Stunned By Victoria Azarenka I...     SPORTS   
209524  Giants Over Patriots, Jets Over Colts Among  M...     SPORTS   
209525  Aldon Smith Arrested: 49ers Linebacker Busted ...     SPORTS   
209526  Dwight Howard Rips Teammates After Magic Loss ...     SPORTS   

                                        short_description  \
0       Health experts said it is too early to predict...   
1       He was subdued by passengers and crew when he ...   
2       "Until you have a dog you don't understand wha...   
3       "Accidentally put grown-up toothpaste on my to...   
4       Amy Cooper accused investment firm Franklin Te...   
...                                                   ...   
209522  Verizon Wireless and AT&T are already promotin...   
209523  Afterward, Azarenka, more effusive with the pr...   
209524  Leading up to Super Bowl XLVI, the most talked...   
209525  CORRECTION: An earlier version of this story i...   
209526  The five-time all-star center tore into his te...   

                     authors       date  
0       Carla K. Johnson, AP 2022-09-23  
1             Mary Papenfuss 2022-09-23  
2              Elyse Wanshel 2022-09-23  
3           Caroline Bologna 2022-09-23  
4             Nina Golgowski 2022-09-22  
...                      ...        ...  
209522      Reuters, Reuters 2012-01-28  
209523                       2012-01-28  
209524                       2012-01-28  
209525                       2012-01-28  
209526                       2012-01-28  

[209527 rows x 6 columns]

In [48]:
cats = set(data['category'])
len(cats)

42

In [49]:
counts = Counter(data['category'])
counts

Counter({'POLITICS': 35602,
         'WELLNESS': 17945,
         'ENTERTAINMENT': 17362,
         'TRAVEL': 9900,
         'STYLE & BEAUTY': 9814,
         'PARENTING': 8791,
         'HEALTHY LIVING': 6694,
         'QUEER VOICES': 6347,
         'FOOD & DRINK': 6340,
         'BUSINESS': 5992,
         'COMEDY': 5400,
         'SPORTS': 5077,
         'BLACK VOICES': 4583,
         'HOME & LIVING': 4320,
         'PARENTS': 3955,
         'THE WORLDPOST': 3664,
         'WEDDINGS': 3653,
         'WOMEN': 3572,
         'CRIME': 3562,
         'IMPACT': 3484,
         'DIVORCE': 3426,
         'WORLD NEWS': 3299,
         'MEDIA': 2944,
         'WEIRD NEWS': 2777,
         'GREEN': 2622,
         'WORLDPOST': 2579,
         'RELIGION': 2577,
         'STYLE': 2254,
         'SCIENCE': 2206,
         'TECH': 2104,
         'TASTE': 2096,
         'MONEY': 1756,
         'ARTS': 1509,
         'ENVIRONMENT': 1444,
         'FIFTY': 1401,
         'GOOD NEWS': 1398,
         'U.S. NEWS

In [50]:
final_cats = []
for i in counts:
    if counts[i] > 8000:
        final_cats.append(i)
final_cats

['PARENTING',
 'ENTERTAINMENT',
 'POLITICS',
 'WELLNESS',
 'STYLE & BEAUTY',
 'TRAVEL']

In [51]:
data = data.reset_index()

In [52]:
x = []
y = []

for index, row in data.iterrows():
    if row[3] in final_cats:
        x.append(row[4])
        y.append(row[3])

C:\Users\HP\AppData\Local\Temp\ipykernel_8056\1848667952.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[3] in final_cats:
C:\Users\HP\AppData\Local\Temp\ipykernel_8056\1848667952.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  x.append(row[4])
C:\Users\HP\AppData\Local\Temp\ipykernel_8056\1848667952.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  y.append(row[3])


In [53]:
print(len(x))
print(len(y))

99414
99414


In [57]:
from sklearn.preprocessing import LabelEncoder

In [58]:
encoder = LabelEncoder()
class_labels = encoder.fit_transform(y)

In [59]:
set(class_labels)

{0, 1, 2, 3, 4, 5}

In [60]:
from sklearn.preprocessing import OneHotEncoder

In [61]:
encoder = OneHotEncoder(sparse_output=False)
class_labels = class_labels.reshape((class_labels.shape[0], 1))
y_ohe = encoder.fit_transform(class_labels)

In [62]:
print(y_ohe)
print(y_ohe.shape)

[[0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
(99414, 6)


In [63]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [64]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)

X_token = tokenizer.texts_to_sequences(x)

vocab_size = len(tokenizer.word_index) + 1

In [65]:
vocab_size

60787

In [66]:
print(x[0])
print(X_token[0])
print(len(x[0]))
print(len(X_token[0]))

"Accidentally put grown-up toothpaste on my toddler’s toothbrush and he screamed like I was cleaning his teeth with a Carolina Reaper dipped in Tabasco sauce."
[6145, 275, 1722, 50, 15527, 12, 28, 34124, 19085, 4, 48, 14301, 56, 11, 24, 4567, 43, 3009, 14, 3, 1764, 26082, 14302, 6, 34125, 9504]
159
26


In [67]:
from keras.preprocessing.sequence import pad_sequences

In [68]:
maxlen = 100
X_pad = pad_sequences(X_token, padding='post', maxlen=maxlen)

In [69]:
word_ls = []
for sen in x:
    word_ls.extend(sen.split())
print(len(word_ls))
counter = Counter(word_ls)
most_occur = counter.most_common(100)
print(most_occur)

2078075
[('the', 87344), ('to', 58816), ('of', 49098), ('a', 48235), ('and', 46581), ('in', 29804), ('is', 24510), ('that', 21613), ('for', 19226), ('The', 17815), ('I', 15777), ('on', 15498), ('you', 14133), ('with', 13183), ('are', 13138), ('be', 10745), ('it', 10349), ('have', 9804), ('we', 9360), ('as', 9191), ('was', 8771), ('your', 8752), ('at', 8334), ('not', 7827), ('from', 7642), ('this', 7383), ('our', 7189), ('about', 7020), ('or', 6899), ('has', 6857), ('--', 6806), ('an', 6760), ('my', 6686), ('can', 6682), ('more', 6237), ('but', 6196), ('by', 5603), ('their', 5556), ('will', 5315), ('his', 5300), ('all', 5237), ('out', 5235), ('one', 5021), ('who', 4931), ('what', 4919), ('her', 4639), ('they', 4573), ('when', 4343), ('just', 4088), ('up', 4014), ('he', 3917), ('like', 3910), ('do', 3731), ('been', 3683), ('than', 3635), ('new', 3607), ('some', 3521), ('But', 3516), ('time', 3457), ('people', 3377), ('how', 3373), ('so', 3244), ('get', 3129), ('In', 3028), ('would', 3022

In [70]:
X_pad.shape

(99414, 100)

In [71]:
X_pad[0]

array([ 6145,   275,  1722,    50, 15527,    12,    28, 34124, 19085,
           4,    48, 14301,    56,    11,    24,  4567,    43,  3009,
          14,     3,  1764, 26082, 14302,     6, 34125,  9504,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0])

In [72]:
c_l = list(class_labels[:,0])
c_l = set(c_l)
class_weight = {}

for c in (list(c_l)):
    print(c)
    c_w = len(class_labels)/np.sum(class_labels==c)
    print(c_w)
    class_weight[c] = c_w

0
5.725953231194563
1
11.308611079513138
2
2.792371215100275
3
10.12981455064194
4
10.041818181818181
5
5.539927556422402


In [73]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Bidirectional, Dense

In [74]:
vocab_size

60787

In [75]:
embedding_dim = 3

model = Sequential()
model.add(Embedding(input_dim=vocab_size, 
                           output_dim=embedding_dim))
model.add(Bidirectional(LSTM(128, return_sequences = True)))
model.add(Bidirectional(LSTM(128))) 
model.add(Dense(6, activation='softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_16                │ ?                      │   0 (unbuilt) │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_17                │ ?                      │   0 (unbuilt) │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
from keras.callbacks import LearningRateScheduler, EarlyStopping
from math import exp

In [31]:
def exp_decay(epoch):
    initial_lrate = 0.1
    k = 0.1
    lrate = initial_lrate * exp(-k*epoch)
    return lrate
lrate = LearningRateScheduler(exp_decay)

In [32]:

[exp_decay(i) for i in range(5)]

[0.1,
 0.09048374180359596,
 0.0818730753077982,
 0.0740818220681718,
 0.06703200460356394]

In [33]:
from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits=2, test_size=0.3, random_state=0)
sss.get_n_splits(X_pad, y_ohe)

#print(sss)       

for train_index, test_index in sss.split(X_pad, y_ohe):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X_pad[train_index], X_pad[test_index]
    y_train, y_test = y_ohe[train_index], y_ohe[test_index]

In [34]:
history = model.fit(X_train, y_train,
                    epochs=10,
                    verbose=1,
                    validation_split=0.2,
                    batch_size=256,
                    class_weight = class_weight)

Epoch 1/10


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 6), output.shape=(None, 9)

In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.legend(['train', 'valid'])
plt.show()

In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.legend(['train', 'valid'])
plt.show()

In [ ]:
model.save('lstm_best.h5')

In [ ]:
plt.hist(y_train)
plt.show()